export const PACKET_LIST_REQUEST = 'PACKET_LIST_REQUEST';
export const PACKET_LIST_SUCCESS = 'PACKET_LIST_SUCCESS';
export const PACKET_LIST_FAIL = 'PACKET_LIST_FAIL';

export const PACKET_CREATE_REQUEST = 'PACKET_CREATE_REQUEST';
export const PACKET_CREATE_SUCCESS = 'PACKET_CREATE_SUCCESS';
export const PACKET_CREATE_FAIL = 'PACKET_CREATE_FAIL';
export const PACKET_CREATE_RESET = 'PACKET_CREATE_RESET'

export const PACKET_DETAILS_REQUEST = 'PACKET_DETAILS_REQUEST'
export const PACKET_DETAILS_SUCCESS = 'PACKET_DETAILS_SUCCESS'
export const PACKET_DETAILS_FAIL = 'PACKET_DETAILS_FAIL'

export const PACKET_UPDATE_REQUEST = 'PACKET_UPDATE_REQUEST';
export const PACKET_UPDATE_SUCCESS = 'PACKET_UPDATE_SUCCESS';
export const PACKET_UPDATE_FAIL = 'PACKET_UPDATE_FAIL';
export const PACKET_UPDATE_RESET = 'PACKET_UPDATE_RESET'

export const PACKET_DELETE_REQUEST = 'PACKET_DELETE_REQUEST';
export const PACKET_DELETE_SUCCESS = 'PACKET_DELETE_SUCCESS';
export const PACKET_DELETE_FAIL = 'PACKET_DELETE_FAIL';

export const PACKET_SEARCH_REQUEST = 'PACKET_SEARCH_REQUEST';
export const PACKET_SEARCH_SUCCESS = 'PACKET_SEARCH_SUCCESS';
export const PACKET_SEARCH_FAIL = 'PACKET_SEARCH_FAIL';
