export const POWDER_LIST_REQUEST = 'POWDER_LIST_REQUEST';
export const POWDER_LIST_SUCCESS = 'POWDER_LIST_SUCCESS';
export const POWDER_LIST_FAIL = 'POWDER_LIST_FAIL';

export const POWDER_CREATE_REQUEST = 'POWDER_CREATE_REQUEST';
export const POWDER_CREATE_SUCCESS = 'POWDER_CREATE_SUCCESS';
export const POWDER_CREATE_FAIL = 'POWDER_CREATE_FAIL';
export const POWDER_CREATE_RESET = 'POWDER_CREATE_RESET'

export const POWDER_DETAILS_REQUEST = 'POWDER_DETAILS_REQUEST'
export const POWDER_DETAILS_SUCCESS = 'POWDER_DETAILS_SUCCESS'
export const POWDER_DETAILS_FAIL = 'POWDER_DETAILS_FAIL'

export const POWDER_UPDATE_REQUEST = 'POWDER_UPDATE_REQUEST';
export const POWDER_UPDATE_SUCCESS = 'POWDER_UPDATE_SUCCESS';
export const POWDER_UPDATE_FAIL = 'POWDER_UPDATE_FAIL';
export const POWDER_UPDATE_RESET = 'POWDER_UPDATE_RESET'

export const POWDER_DELETE_REQUEST = 'POWDER_DELETE_REQUEST';
export const POWDER_DELETE_SUCCESS = 'POWDER_DELETE_SUCCESS';
export const POWDER_DELETE_FAIL = 'POWDER_DELETE_FAIL';
