export const SACK_LIST_REQUEST = 'SACK_LIST_REQUEST';
export const SACK_LIST_SUCCESS = 'SACK_LIST_SUCCESS';
export const SACK_LIST_FAIL = 'SACK_LIST_FAIL';

export const SACK_CREATE_REQUEST = 'SACK_CREATE_REQUEST';
export const SACK_CREATE_SUCCESS = 'SACK_CREATE_SUCCESS';
export const SACK_CREATE_FAIL = 'SACK_CREATE_FAIL';
export const SACK_CREATE_RESET = 'SACK_CREATE_RESET'

export const SACK_DETAILS_REQUEST = 'SACK_DETAILS_REQUEST'
export const SACK_DETAILS_SUCCESS = 'SACK_DETAILS_SUCCESS'
export const SACK_DETAILS_FAIL = 'SACK_DETAILS_FAIL'

export const SACK_UPDATE_REQUEST = 'SACK_UPDATE_REQUEST';
export const SACK_UPDATE_SUCCESS = 'SACK_UPDATE_SUCCESS';
export const SACK_UPDATE_FAIL = 'SACK_UPDATE_FAIL';
export const SACK_UPDATE_RESET = 'SACK_UPDATE_RESET'

export const SACK_DELETE_REQUEST = 'SACK_DELETE_REQUEST';
export const SACK_DELETE_SUCCESS = 'SACK_DELETE_SUCCESS';
export const SACK_DELETE_FAIL = 'SACK_DELETE_FAIL';
